### PR TITLE
Add container image build

### PR DESCRIPTION
**Pull request by lazyfrosch**
And publish the image to GitHub container registry.

Let me here your thoughts.

### CODE REVIEW

**Comment by loafoe** [comment]
@lazyfrosch thanks! I'm not familiar with `ghcr.io` . Would the project be on the hook for any data transfer costs if folks start consuming this image ?

**Comment by lazyfrosch** [comment]
As long as the image is public, no. But you would need to check with the org admin if public images are enabled and of course allowed/wanted from your side 😉

**Comment by loafoe** [comment]
Ok, I guess this is a good test for that, merging.

**Comment by lazyfrosch** [comment]
If you create a new tag, the container will be built with that version and the `latest` tag will be set as well.

**Pull request merged**
